name: CI

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/checkout@v4
      - name: Running ruff checks
        uses: astral-sh/ruff-action@v3
        with:
          args: "check . --diff"
  main:
    runs-on: ubuntu-latest
    needs: ruff
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt -r requirements.dev.txt

      - name: Run Mypy
        run: uv run mypy

      - name: Run Pytest
        run: uv run python -m pytest